name: ChunkLimiter
version: '1.0'
main: net.weesli.chunklimiter.ChunkLimiter
api-version: '1.13'
author: Weesli
commands:
  chunklimiter:
    description: main commands for plugin


permissions:
  chunklimiter.bypass:
    description: unlock all limits